# -*- coding: utf-8 -*-
"""Market_Basket_Analysis_using_ECLAT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17nrZoLNS7ol_mh7MnFHStzcxgoBPSdMY

### Importing the basic libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""### Load Dataset from Local Directory"""

from google.colab import files
uploaded = files.upload()

"""### Importing the dataset"""

dataset = pd.read_csv('dataset.csv')
print(dataset.shape)
print(dataset.head(5))

""" ### Upper Confidence bound"""

import math
observations = 10000
no_of_Ads = 10
ads_selected = []
numbers_of_selections_of_each_ads = [0] * no_of_Ads
sums_of_rewards_of_each_ads = [0] * no_of_Ads
total_reward = 0
for n in range(0, observations):
    ad = 0
    max_upper_bound = 0
    for i in range(0, no_of_Ads):
        if (numbers_of_selections_of_each_ads[i] > 0):
            average_reward = sums_of_rewards_of_each_ads[i] / numbers_of_selections_of_each_ads[i]
            delta_i = math.sqrt(3/2 * math.log(n + 1) / numbers_of_selections_of_each_ads[i])
            upper_bound = average_reward + delta_i
        else:
            upper_bound = 1e400
        if upper_bound > max_upper_bound:
            max_upper_bound = upper_bound
            ad = i
    ad_selected.append(ad)
    no_selection_eachAd[ad] = no_selection_eachAd[ad] + 1
    reward = dataset.values[n, ad]
    sum_reward_eachAd[ad] = sum_reward_eachAd[ad] + reward
    total_reward = total_reward + reward

print("Rewards by Ads = ",sum_reward_eachAd)
print("Total Rewards by UCB = ",total_reward)
print("Ads selected at each round:",ad_selected)

"""### Visualize result """

plt.hist(ad_selected)
plt.title('Histogram of ads selections')
plt.xlabel('Ads')
plt.ylabel('Number of times each ad was selected')
plt.show()